import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync, existsSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import { generateScrybeIgnore } from "../src/onboarding/scrybeignore.js";

let tmp = "";

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "scrybe-ig-test-"));
});

afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

describe("generateScrybeIgnore", () => {
  it("generates file when none exists", () => {
    const result = generateScrybeIgnore(tmp);
    expect(result.wasGenerated).toBe(true);
    expect(result.content).toContain("node_modules/");
    expect(result.content).toContain("# Generated by scrybe init");
  });

  it("returns existing without overwriting", () => {
    const existing = "# my custom rules\nfoo/\n";
    writeFileSync(join(tmp, ".scrybeignore"), existing);
    const result = generateScrybeIgnore(tmp);
    expect(result.wasGenerated).toBe(false);
    expect(result.content).toBe(existing);
    expect(result.existingPath).toBeDefined();
  });

  it("merges patterns from .gitignore", () => {
    writeFileSync(join(tmp, ".gitignore"), "node_modules\n*.log\nsecret.env\n");
    const result = generateScrybeIgnore(tmp);
    expect(result.wasGenerated).toBe(true);
    expect(result.content).toContain("*.log");
    expect(result.content).toContain("secret.env");
    expect(result.notes.some((n) => n.includes(".gitignore"))).toBe(true);
  });

  it("generates without .gitignore present", () => {
    const result = generateScrybeIgnore(tmp);
    expect(result.wasGenerated).toBe(true);
    expect(result.content).toContain("dist/");
    expect(result.notes.some((n) => n.includes("standard skip"))).toBe(true);
  });

  it("includes standard skips for .NET project", () => {
    const result = generateScrybeIgnore(tmp);
    expect(result.content).toContain("obj/");
    expect(result.content).toContain("bin/");
    expect(result.content).toContain("*.g.cs");
  });
});
