import { spawn } from "child_process";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import { config } from "../config.js";

/**
 * Spawns `scrybe daemon start` as a detached, fully independent process.
 * The spawned process is unref'd immediately so it outlives the parent.
 *
 * On Windows, routes through a tiny wscript.exe + VBS launcher because
 * spawning node.exe directly — even with `windowsHide: true` and
 * `detached: true` — briefly flashes a console window during node init.
 * wscript.exe is a GUI-subsystem binary, so it allocates no console at all,
 * and `Run(cmd, 0, false)` launches the child fully hidden.
 *
 * Uses process.execPath (node binary) + process.argv[1] (dist/index.js or the
 * globally-installed scrybe script) so it works in both dev and production.
 */
export function spawnDaemonDetached(opts: {
  execPath?: string;
  entryScript?: string;
  env?: NodeJS.ProcessEnv;
}): void {
  const node   = opts.execPath   ?? process.execPath;
  const script = opts.entryScript ?? process.argv[1]!;
  const env    = opts.env ?? process.env;

  if (process.platform === "win32") {
    const vbs = ensureWindowsLauncherVbs();
    const child = spawn("wscript.exe", [vbs, node, script], {
      detached: true,
      stdio: "ignore",
      windowsHide: true,
      env,
    });
    child.unref();
    return;
  }

  const child = spawn(node, [script, "daemon", "start"], {
    detached: true,
    stdio: "ignore",
    windowsHide: true,
    env,
  });
  child.unref();
}

/**
 * Writes (idempotently) a VBS launcher into DATA_DIR that runs
 * `<node> <script> daemon start` with a hidden window via WScript.Shell.Run.
 * Returns the absolute path to the .vbs file.
 */
function ensureWindowsLauncherVbs(): string {
  const dir = config.dataDir;
  mkdirSync(dir, { recursive: true });
  const vbsPath = join(dir, "daemon-spawn.vbs");
  if (existsSync(vbsPath)) return vbsPath;

  const vbs = [
    "' Auto-generated by scrybe - launches the daemon with no console flash.",
    "Set sh = CreateObject(\"WScript.Shell\")",
    "Dim cmd",
    "cmd = \"\"\"\" & WScript.Arguments(0) & \"\"\" \"\"\" & WScript.Arguments(1) & \"\"\" daemon start\"",
    "sh.Run cmd, 0, False",
  ].join("\r\n") + "\r\n";

  writeFileSync(vbsPath, vbs, "utf8");
  return vbsPath;
}
