import { spawn } from "child_process";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import { config } from "../config.js";
import { diagEmit } from "./events.js";

/**
 * Merges glibc allocator-arena caps into a daemon spawn env, respecting any
 * value the user has already set. `MALLOC_ARENA_MAX=2` + a lower trim
 * threshold stop glibc from hoarding freed memory in per-thread arenas —
 * measured ~793 MB -> ~128 MB retained RSS after sustained vector scans
 * (see ADR-0009). glibc reads these at process init, so they must be present
 * in the child's env at spawn time, not set afterward. No-op on
 * Windows/musl (different allocator) — harmless to set unconditionally.
 */
export function daemonSpawnEnv(base: NodeJS.ProcessEnv = process.env): NodeJS.ProcessEnv {
  return {
    ...base,
    MALLOC_ARENA_MAX: base.MALLOC_ARENA_MAX ?? "2",
    MALLOC_TRIM_THRESHOLD_: base.MALLOC_TRIM_THRESHOLD_ ?? "131072",
  };
}

/**
 * Spawns `scrybe daemon start` as a detached, fully independent process.
 * The spawned process is unref'd immediately so it outlives the parent.
 *
 * On Windows, routes through a tiny wscript.exe + VBS launcher because
 * spawning node.exe directly — even with `windowsHide: true` and
 * `detached: true` — briefly flashes a console window during node init.
 * wscript.exe is a GUI-subsystem binary, so it allocates no console at all,
 * and `Run(cmd, 0, false)` launches the child fully hidden.
 *
 * Uses process.execPath (node binary) + process.argv[1] (dist/index.js or the
 * globally-installed scrybe script) so it works in both dev and production.
 */
export function spawnDaemonDetached(opts: {
  execPath?: string;
  entryScript?: string;
  env?: NodeJS.ProcessEnv;
}): void {
  const node   = opts.execPath   ?? process.execPath;
  const script = opts.entryScript ?? process.argv[1]!;
  const env    = daemonSpawnEnv(opts.env ?? process.env);

  if (process.platform === "win32") {
    const vbs = ensureWindowsLauncherVbs();
    const child = spawn("wscript.exe", [vbs, node, script], {
      detached: true,
      stdio: "ignore",
      windowsHide: true,
      env,
    });
    diagEmit({
      event: "child-process.spawn",
      level: "info",
      pid: child.pid ?? null,
      ppid: process.pid,
      command: "wscript.exe",
      args: [vbs, node, script],
      detached: true,
    });
    child.once("exit", (code, signal) => {
      diagEmit({
        event: "child-process.exit",
        level: "info",
        pid: child.pid ?? null,
        ppid: process.pid,
        exitCode: code,
        signal: signal ?? null,
      });
    });
    child.unref();
    return;
  }

  const child = spawn(node, [script, "daemon", "start"], {
    detached: true,
    stdio: "ignore",
    windowsHide: true,
    env,
  });
  diagEmit({
    event: "child-process.spawn",
    level: "info",
    pid: child.pid ?? null,
    ppid: process.pid,
    command: node,
    args: [script, "daemon", "start"],
    detached: true,
  });
  child.once("exit", (code, signal) => {
    diagEmit({
      event: "child-process.exit",
      level: "info",
      pid: child.pid ?? null,
      ppid: process.pid,
      exitCode: code,
      signal: signal ?? null,
    });
  });
  child.unref();
}

/**
 * Writes (idempotently) a VBS launcher into DATA_DIR that runs
 * `<node> <script> daemon start` with a hidden window via WScript.Shell.Run.
 * Returns the absolute path to the .vbs file.
 */
function ensureWindowsLauncherVbs(): string {
  const dir = config.dataDir;
  mkdirSync(dir, { recursive: true });
  const vbsPath = join(dir, "daemon-spawn.vbs");
  if (existsSync(vbsPath)) return vbsPath;

  const vbs = [
    "' Auto-generated by scrybe - launches the daemon with no console flash.",
    "Set sh = CreateObject(\"WScript.Shell\")",
    "Dim cmd",
    "cmd = \"\"\"\" & WScript.Arguments(0) & \"\"\" \"\"\" & WScript.Arguments(1) & \"\"\" daemon start\"",
    "sh.Run cmd, 0, False",
  ].join("\r\n") + "\r\n";

  writeFileSync(vbsPath, vbs, "utf8");
  return vbsPath;
}
