import { existsSync, readFileSync } from "fs";
import { join } from "path";

export interface GenerateResult {
  content: string;
  wasGenerated: boolean;
  existingPath?: string;
  notes: string[];
}

// Mirrors the SKIP_DIRS in src/chunker.ts — keep in sync
const STANDARD_SKIPS = [
  "node_modules/",
  "dist/",
  "build/",
  ".next/",
  ".nuxt/",
  "coverage/",
  "target/",
  "bin/",
  "obj/",
  ".vs/",
  "TestResults/",
  "publish/",
  "artifacts/",
  "__pycache__/",
  ".venv/",
  "venv/",
  "vendor/",
  "android/",
  "ios/",
  "electron/",
  "fastlane/",
  "packages/",
];

const STANDARD_FILE_SKIPS = [
  "*.lock",
  "*.map",
  "*.min.js",
  "*.min.css",
  "*.g.cs",
  "*.designer.cs",
  "*.Designer.cs",
  "*.generated.cs",
];

export function generateScrybeIgnore(projectRoot: string): GenerateResult {
  const scrybeignorePath = join(projectRoot, ".scrybeignore");
  const notes: string[] = [];

  // Don't overwrite existing
  if (existsSync(scrybeignorePath)) {
    return {
      content: readFileSync(scrybeignorePath, "utf8"),
      wasGenerated: false,
      existingPath: scrybeignorePath,
      notes: ["Existing .scrybeignore found — not overwritten"],
    };
  }

  const lines: string[] = ["# Generated by scrybe init", ""];

  // Merge from .gitignore if present
  const gitignorePath = join(projectRoot, ".gitignore");
  if (existsSync(gitignorePath)) {
    const gitignoreLines = readFileSync(gitignorePath, "utf8")
      .split("\n")
      .map((l) => l.trimEnd())
      .filter((l) => l && !l.startsWith("#"));
    if (gitignoreLines.length > 0) {
      lines.push("# From .gitignore");
      lines.push(...gitignoreLines);
      lines.push("");
      notes.push(`Merged ${gitignoreLines.length} pattern(s) from .gitignore`);
    }
  }

  // Add standard skips that aren't already covered
  const existingPatterns = new Set(lines.map((l) => l.toLowerCase()));
  const toAdd = [...STANDARD_SKIPS, ...STANDARD_FILE_SKIPS].filter(
    (p) => !existingPatterns.has(p.toLowerCase())
  );
  if (toAdd.length > 0) {
    lines.push("# Standard scrybe skips");
    lines.push(...toAdd);
    lines.push("");
    notes.push(`Added ${toAdd.length} standard skip pattern(s)`);
  }

  return {
    content: lines.join("\n"),
    wasGenerated: true,
    notes,
  };
}
